export const CURRENCIES = [
  { code: 'AED', label: 'AED', name: 'UAE Dirham' },
  { code: 'AFN', label: 'AFN', name: 'Afghan Afghani' },
  { code: 'ALL', label: 'ALL', name: 'Albanian Lek' },
  { code: 'AMD', label: 'AMD', name: 'Armenian Dram' },
  { code: 'AOA', label: 'AOA', name: 'Angolan Kwanza' },
  { code: 'ARS', label: 'ARS', name: 'Argentine Peso' },
  { code: 'AUD', label: 'AUD', name: 'Australian Dollar' },
  { code: 'AWG', label: 'AWG', name: 'Aruban Florin' },
  { code: 'AZN', label: 'AZN', name: 'Azerbaijani Manat' },
  { code: 'BAM', label: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark' },
  { code: 'BBD', label: 'BBD', name: 'Barbadian Dollar' },
  { code: 'BDT', label: 'BDT', name: 'Bangladeshi Taka' },
  { code: 'BGN', label: 'BGN', name: 'Bulgarian Lev' },
  { code: 'BHD', label: 'BHD', name: 'Bahraini Dinar' },
  { code: 'BIF', label: 'BIF', name: 'Burundian Franc' },
  { code: 'BMD', label: 'BMD', name: 'Bermudian Dollar' },
  { code: 'BND', label: 'BND', name: 'Brunei Dollar' },
  { code: 'BOB', label: 'BOB', name: 'Bolivian Boliviano' },
  { code: 'BRL', label: 'BRL', name: 'Brazilian Real' },
  { code: 'BSD', label: 'BSD', name: 'Bahamian Dollar' },
  { code: 'BTN', label: 'BTN', name: 'Bhutanese Ngultrum' },
  { code: 'BWP', label: 'BWP', name: 'Botswana Pula' },
  { code: 'BYN', label: 'BYN', name: 'Belarusian Ruble' },
  { code: 'BZD', label: 'BZD', name: 'Belize Dollar' },
  { code: 'CAD', label: 'CAD', name: 'Canadian Dollar' },
  { code: 'CDF', label: 'CDF', name: 'Congolese Franc' },
  { code: 'CHF', label: 'CHF', name: 'Swiss Franc' },
  { code: 'CLP', label: 'CLP', name: 'Chilean Peso' },
  { code: 'CNY', label: 'CNY', name: 'Chinese Yuan' },
  { code: 'COP', label: 'COP', name: 'Colombian Peso' },
  { code: 'CRC', label: 'CRC', name: 'Costa Rican Colón' },
  { code: 'CUP', label: 'CUP', name: 'Cuban Peso' },
  { code: 'CVE', label: 'CVE', name: 'Cape Verdean Escudo' },
  { code: 'CZK', label: 'CZK', name: 'Czech Koruna' },
  { code: 'DJF', label: 'DJF', name: 'Djiboutian Franc' },
  { code: 'DKK', label: 'DKK', name: 'Danish Krone' },
  { code: 'DOP', label: 'DOP', name: 'Dominican Peso' },
  { code: 'DZD', label: 'DZD', name: 'Algerian Dinar' },
  { code: 'EGP', label: 'EGP', name: 'Egyptian Pound' },
  { code: 'ERN', label: 'ERN', name: 'Eritrean Nakfa' },
  { code: 'ETB', label: 'ETB', name: 'Ethiopian Birr' },
  { code: 'EUR', label: 'EUR', name: 'Euro' },
  { code: 'FJD', label: 'FJD', name: 'Fijian Dollar' },
  { code: 'FKP', label: 'FKP', name: 'Falkland Islands Pound' },
  { code: 'GBP', label: 'GBP', name: 'British Pound' },
  { code: 'GEL', label: 'GEL', name: 'Georgian Lari' },
  { code: 'GHS', label: 'GHS', name: 'Ghanaian Cedi' },
  { code: 'GIP', label: 'GIP', name: 'Gibraltar Pound' },
  { code: 'GMD', label: 'GMD', name: 'Gambian Dalasi' },
  { code: 'GNF', label: 'GNF', name: 'Guinean Franc' },
  { code: 'GTQ', label: 'GTQ', name: 'Guatemalan Quetzal' },
  { code: 'GYD', label: 'GYD', name: 'Guyanese Dollar' },
  { code: 'HKD', label: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'HNL', label: 'HNL', name: 'Honduran Lempira' },
  { code: 'HTG', label: 'HTG', name: 'Haitian Gourde' },
  { code: 'HUF', label: 'HUF', name: 'Hungarian Forint' },
  { code: 'IDR', label: 'IDR', name: 'Indonesian Rupiah' },
  { code: 'ILS', label: 'ILS', name: 'Israeli New Shekel' },
  { code: 'INR', label: 'INR', name: 'Indian Rupee' },
  { code: 'IQD', label: 'IQD', name: 'Iraqi Dinar' },
  { code: 'IRR', label: 'IRR', name: 'Iranian Rial' },
  { code: 'ISK', label: 'ISK', name: 'Icelandic Króna' },
  { code: 'JMD', label: 'JMD', name: 'Jamaican Dollar' },
  { code: 'JOD', label: 'JOD', name: 'Jordanian Dinar' },
  { code: 'JPY', label: 'JPY', name: 'Japanese Yen' },
  { code: 'KES', label: 'KES', name: 'Kenyan Shilling' },
  { code: 'KGS', label: 'KGS', name: 'Kyrgyzstani Som' },
  { code: 'KHR', label: 'KHR', name: 'Cambodian Riel' },
  { code: 'KMF', label: 'KMF', name: 'Comorian Franc' },
  { code: 'KPW', label: 'KPW', name: 'North Korean Won' },
  { code: 'KRW', label: 'KRW', name: 'South Korean Won' },
  { code: 'KWD', label: 'KWD', name: 'Kuwaiti Dinar' },
  { code: 'KYD', label: 'KYD', name: 'Cayman Islands Dollar' },
  { code: 'KZT', label: 'KZT', name: 'Kazakhstani Tenge' },
  { code: 'LAK', label: 'LAK', name: 'Lao Kip' },
  { code: 'LBP', label: 'LBP', name: 'Lebanese Pound' },
  { code: 'LKR', label: 'LKR', name: 'Sri Lankan Rupee' },
  { code: 'LRD', label: 'LRD', name: 'Liberian Dollar' },
  { code: 'LSL', label: 'LSL', name: 'Lesotho Loti' },
  { code: 'LYD', label: 'LYD', name: 'Libyan Dinar' },
  { code: 'MAD', label: 'MAD', name: 'Moroccan Dirham' },
  { code: 'MDL', label: 'MDL', name: 'Moldovan Leu' },
  { code: 'MGA', label: 'MGA', name: 'Malagasy Ariary' },
  { code: 'MKD', label: 'MKD', name: 'Macedonian Denar' },
  { code: 'MMK', label: 'MMK', name: 'Myanmar Kyat' },
  { code: 'MNT', label: 'MNT', name: 'Mongolian Tögrög' },
  { code: 'MOP', label: 'MOP', name: 'Macanese Pataca' },
  { code: 'MRU', label: 'MRU', name: 'Mauritanian Ouguiya' },
  { code: 'MUR', label: 'MUR', name: 'Mauritian Rupee' },
  { code: 'MVR', label: 'MVR', name: 'Maldivian Rufiyaa' },
  { code: 'MWK', label: 'MWK', name: 'Malawian Kwacha' },
  { code: 'MXN', label: 'MXN', name: 'Mexican Peso' },
  { code: 'MYR', label: 'MYR', name: 'Malaysian Ringgit' },
  { code: 'MZN', label: 'MZN', name: 'Mozambican Metical' },
  { code: 'NAD', label: 'NAD', name: 'Namibian Dollar' },
  { code: 'NGN', label: 'NGN', name: 'Nigerian Naira' },
  { code: 'NIO', label: 'NIO', name: 'Nicaraguan Córdoba' },
  { code: 'NOK', label: 'NOK', name: 'Norwegian Krone' },
  { code: 'NPR', label: 'NPR', name: 'Nepalese Rupee' },
  { code: 'NZD', label: 'NZD', name: 'New Zealand Dollar' },
  { code: 'OMR', label: 'OMR', name: 'Omani Rial' },
  { code: 'PAB', label: 'PAB', name: 'Panamanian Balboa' },
  { code: 'PEN', label: 'PEN', name: 'Peruvian Sol' },
  { code: 'PGK', label: 'PGK', name: 'Papua New Guinean Kina' },
  { code: 'PHP', label: 'PHP', name: 'Philippine Peso' },
  { code: 'PKR', label: 'PKR', name: 'Pakistani Rupee' },
  { code: 'PLN', label: 'PLN', name: 'Polish Złoty' },
  { code: 'PYG', label: 'PYG', name: 'Paraguayan Guaraní' },
  { code: 'QAR', label: 'QAR', name: 'Qatari Riyal' },
  { code: 'RON', label: 'RON', name: 'Romanian Leu' },
  { code: 'RSD', label: 'RSD', name: 'Serbian Dinar' },
  { code: 'RUB', label: 'RUB', name: 'Russian Ruble' },
  { code: 'RWF', label: 'RWF', name: 'Rwandan Franc' },
  { code: 'SAR', label: 'SAR', name: 'Saudi Riyal' },
  { code: 'SBD', label: 'SBD', name: 'Solomon Islands Dollar' },
  { code: 'SCR', label: 'SCR', name: 'Seychellois Rupee' },
  { code: 'SDG', label: 'SDG', name: 'Sudanese Pound' },
  { code: 'SEK', label: 'SEK', name: 'Swedish Krona' },
  { code: 'SGD', label: 'SGD', name: 'Singapore Dollar' },
  { code: 'SHP', label: 'SHP', name: 'Saint Helena Pound' },
  { code: 'SLE', label: 'SLE', name: 'Sierra Leonean Leone' },
  { code: 'SOS', label: 'SOS', name: 'Somali Shilling' },
  { code: 'SRD', label: 'SRD', name: 'Surinamese Dollar' },
  { code: 'SSP', label: 'SSP', name: 'South Sudanese Pound' },
  { code: 'STN', label: 'STN', name: 'São Tomé and Príncipe Dobra' },
  { code: 'SYP', label: 'SYP', name: 'Syrian Pound' },
  { code: 'SZL', label: 'SZL', name: 'Eswatini Lilangeni' },
  { code: 'THB', label: 'THB', name: 'Thai Baht' },
  { code: 'TJS', label: 'TJS', name: 'Tajikistani Somoni' },
  { code: 'TMT', label: 'TMT', name: 'Turkmenistan Manat' },
  { code: 'TND', label: 'TND', name: 'Tunisian Dinar' },
  { code: 'TOP', label: 'TOP', name: 'Tongan Paʻanga' },
  { code: 'TRY', label: 'TRY', name: 'Turkish Lira' },
  { code: 'TTD', label: 'TTD', name: 'Trinidad and Tobago Dollar' },
  { code: 'TWD', label: 'TWD', name: 'New Taiwan Dollar' },
  { code: 'TZS', label: 'TZS', name: 'Tanzanian Shilling' },
  { code: 'UAH', label: 'UAH', name: 'Ukrainian Hryvnia' },
  { code: 'UGX', label: 'UGX', name: 'Ugandan Shilling' },
  { code: 'USD', label: 'USD', name: 'US Dollar' },
  { code: 'UYU', label: 'UYU', name: 'Uruguayan Peso' },
  { code: 'UZS', label: 'UZS', name: 'Uzbekistani Som' },
  { code: 'VES', label: 'VES', name: 'Venezuelan Bolívar' },
  { code: 'VND', label: 'VND', name: 'Vietnamese Đồng' },
  { code: 'VUV', label: 'VUV', name: 'Vanuatu Vatu' },
  { code: 'WST', label: 'WST', name: 'Samoan Tālā' },
  { code: 'XAF', label: 'XAF', name: 'Central African CFA Franc' },
  { code: 'XCD', label: 'XCD', name: 'East Caribbean Dollar' },
  { code: 'XOF', label: 'XOF', name: 'West African CFA Franc' },
  { code: 'XPF', label: 'XPF', name: 'CFP Franc' },
  { code: 'YER', label: 'YER', name: 'Yemeni Rial' },
  { code: 'ZAR', label: 'ZAR', name: 'South African Rand' },
  { code: 'ZMW', label: 'ZMW', name: 'Zambian Kwacha' },
  { code: 'ZWL', label: 'ZWL', name: 'Zimbabwean Dollar' },
] as const

export type CurrencyCode = (typeof CURRENCIES)[number]['code']

export const DEFAULT_CURRENCY: CurrencyCode = 'MYR'

export const CURRENCY_CODES = CURRENCIES.map((currency) => currency.code)

export function isCurrencyCode(value: string): value is CurrencyCode {
  return CURRENCY_CODES.includes(value as CurrencyCode)
}